language: node_js
node_js:
- "4.2.2"
- "6.8"
- "8.11"

# nodejs version 0.6 is not supported by official node couchbase sdk
# nodejs 0.8 is also not supported by this package
before_script:
    - sudo ln -s $(which node) /bin
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
    - chmod +x /tmp/cc-test-reporter

script:
    - /tmp/cc-test-reporter before-build
    - npm run-script unit-tests
    - npm run-script coverage

after_success:
    - /tmp/cc-test-reporter after-build
    - bash ./deploy.sh
env:
  global:
      - ENCRYPTION_LABEL: 18374567a143
      - COMMIT_AUTHOR_EMAIL: "fogine@opmbx.org"
